/**
 * SQL generation for schema-flow.
 *
 * Renders a migration plan as a standalone .sql file.
 */

import { writeFileSync } from 'node:fs';
import type { Operation, PlanResult } from '../planner/index.js';

export interface GenerateSqlOptions {
  /** Wrap all statements in BEGIN/COMMIT */
  wrapInTransaction?: boolean;
  /** Include blocked (destructive) operations as comments */
  includeBlocked?: boolean;
}

const PHASE_LABELS: Record<number, string> = {
  2: 'Extensions',
  3: 'Enums',
  4: 'Roles',
  5: 'Functions',
  6: 'Tables',
  7: 'Indexes',
  8: 'Foreign Keys',
  9: 'Views',
  10: 'Materialized Views',
  11: 'Triggers',
  12: 'Row-Level Security',
  13: 'Grants',
  14: 'Comments',
  15: 'Seeds',
};

/**
 * Render a migration plan as a SQL string.
 */
export function generateSql(plan: PlanResult, options: GenerateSqlOptions = {}): string {
  const { wrapInTransaction = false, includeBlocked = false } = options;

  if (plan.operations.length === 0 && (!includeBlocked || plan.blocked.length === 0)) {
    return '';
  }

  const lines: string[] = [];

  lines.push(`-- Migration generated by schema-flow`);
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push('');

  // Split concurrent operations (e.g. CREATE INDEX CONCURRENTLY) from transactional ones
  const transactionalOps = plan.operations.filter((op) => !op.concurrent);
  const concurrentOps = plan.operations.filter((op) => op.concurrent);

  if (wrapInTransaction && transactionalOps.length > 0) {
    lines.push('BEGIN;');
    lines.push('');
  }

  // Group transactional operations by phase and emit section comments
  let lastPhase = -1;
  for (const op of transactionalOps) {
    if (op.phase !== lastPhase) {
      if (lastPhase !== -1) lines.push('');
      const label = PHASE_LABELS[op.phase] || `Phase ${op.phase}`;
      lines.push(`-- ${label}`);
      lastPhase = op.phase;
    }
    lines.push(addSemicolon(op.sql));
  }

  if (wrapInTransaction && transactionalOps.length > 0) {
    lines.push('');
    lines.push('COMMIT;');
  }

  // Concurrent operations always appear outside transaction blocks
  if (concurrentOps.length > 0) {
    if (transactionalOps.length > 0) lines.push('');
    lastPhase = -1;
    for (const op of concurrentOps) {
      if (op.phase !== lastPhase) {
        if (lastPhase !== -1) lines.push('');
        const label = PHASE_LABELS[op.phase] || `Phase ${op.phase}`;
        lines.push(`-- ${label} (concurrent, outside transaction)`);
        lastPhase = op.phase;
      }
      lines.push(addSemicolon(op.sql));
    }
  }

  if (includeBlocked && plan.blocked.length > 0) {
    lines.push('');
    lines.push('-- BLOCKED (destructive) — uncomment to apply:');
    for (const op of plan.blocked) {
      lines.push(`-- ${addSemicolon(op.sql)}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Write a migration plan as a SQL file to disk.
 */
export function generateSqlFile(plan: PlanResult, output: string, options: GenerateSqlOptions = {}): void {
  const sql = generateSql(plan, options);
  writeFileSync(output, sql, 'utf-8');
}

/**
 * Format an array of operations as a SQL string.
 */
export function formatMigrationSql(operations: Operation[]): string {
  if (operations.length === 0) return '';
  return operations.map((op) => addSemicolon(op.sql)).join('\n');
}

function addSemicolon(sql: string): string {
  const trimmed = sql.trimEnd();
  return trimmed.endsWith(';') ? trimmed : `${trimmed};`;
}
