import { describe, it, expect, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { useTestProject, writeSchema } from './helpers.js';
import { DATABASE_URL } from './setup.js';
import type { TestProject } from './helpers.js';
import {
  resolveConfig,
  createLogger,
  buildPlan,
  generateSql,
  generateSqlFile,
  generateErd,
  parseTable,
} from '../../src/index.js';
import { buildDesiredAndActual } from '../../src/cli/pipeline.js';

function makeConfig(ctx: TestProject) {
  return resolveConfig({
    connectionString: ctx.config.connectionString,
    baseDir: ctx.dir,
    pgSchema: ctx.schema,
    allowDestructive: false,
  });
}

function makeLogger() {
  return createLogger({ verbose: false, quiet: true, json: false });
}

describe('E2E: SQL generation', () => {
  let ctx: TestProject;

  afterEach(async () => {
    if (ctx) {
      await ctx.cleanup();
    }
  });

  // ─── (1) generateSql produces valid SQL string with BEGIN/COMMIT blocks ──

  it('(1) generateSql produces valid SQL with BEGIN/COMMIT blocks', async () => {
    ctx = await useTestProject(DATABASE_URL);

    writeSchema(ctx.dir, {
      'tables/products.yaml': `
table: products
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
    nullable: false
  - name: price
    type: numeric
`,
    });

    const config = makeConfig(ctx);
    const logger = makeLogger();
    const { desired, actual } = await buildDesiredAndActual(config, logger);
    const plan = buildPlan(desired, actual, {
      allowDestructive: false,
      pgSchema: ctx.schema,
    });

    const sql = generateSql(plan, { wrapInTransaction: true });

    expect(sql).toContain('BEGIN;');
    expect(sql).toContain('COMMIT;');
    expect(sql).toContain('CREATE TABLE');
    expect(sql).toContain('products');
    // Verify it starts with the migration comment header
    expect(sql).toMatch(/^-- Migration generated by schema-flow/);
  });

  // ─── (2) CONCURRENTLY operations appear outside transaction blocks ──

  it('(2) CONCURRENTLY operations appear outside transaction blocks', async () => {
    ctx = await useTestProject(DATABASE_URL);

    writeSchema(ctx.dir, {
      'tables/items.yaml': `
table: items
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
indexes:
  - columns: [name]
    method: btree
`,
    });

    // First, run migration so the table exists
    await ctx.migrate();

    // Now add a concurrent index to the existing table
    writeSchema(ctx.dir, {
      'tables/items.yaml': `
table: items
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
  - name: description
    type: text
indexes:
  - columns: [name]
    method: btree
`,
    });

    const config = makeConfig(ctx);
    const logger = makeLogger();
    const { desired, actual } = await buildDesiredAndActual(config, logger);
    const plan = buildPlan(desired, actual, {
      allowDestructive: false,
      pgSchema: ctx.schema,
    });

    // Mark a concurrent operation manually for testing if none exist naturally
    // The plan should have at least add_column operation
    expect(plan.operations.length).toBeGreaterThan(0);

    // Test the SQL rendering with a fabricated concurrent op
    const concurrentPlan = {
      operations: [
        ...plan.operations,
        {
          type: 'add_index' as const,
          phase: 7,
          objectName: 'items',
          sql: `CREATE INDEX CONCURRENTLY "idx_items_desc" ON "${ctx.schema}"."items" ("description")`,
          destructive: false,
          concurrent: true,
        },
      ],
      blocked: plan.blocked,
    };

    const sql = generateSql(concurrentPlan, { wrapInTransaction: true });

    // BEGIN/COMMIT should wrap non-concurrent ops
    expect(sql).toContain('BEGIN;');
    expect(sql).toContain('COMMIT;');

    // CONCURRENTLY index should appear outside the BEGIN/COMMIT block
    const beginIdx = sql.indexOf('BEGIN;');
    const commitIdx = sql.indexOf('COMMIT;');
    const concurrentIdx = sql.indexOf('CONCURRENTLY');
    expect(concurrentIdx).toBeGreaterThan(commitIdx);
    expect(beginIdx).toBeLessThan(commitIdx);
  });

  // ─── (3) Blocked operations appear as comments ──

  it('(3) blocked operations appear as comments', async () => {
    ctx = await useTestProject(DATABASE_URL);

    writeSchema(ctx.dir, {
      'tables/logs.yaml': `
table: logs
columns:
  - name: id
    type: serial
    primary_key: true
  - name: message
    type: text
  - name: level
    type: text
`,
    });

    // Create the table first
    await ctx.migrate();

    // Remove a column (destructive) without allowDestructive
    writeSchema(ctx.dir, {
      'tables/logs.yaml': `
table: logs
columns:
  - name: id
    type: serial
    primary_key: true
  - name: message
    type: text
`,
    });

    const config = makeConfig(ctx);
    const logger = makeLogger();
    const { desired, actual } = await buildDesiredAndActual(config, logger);
    const plan = buildPlan(desired, actual, {
      allowDestructive: false,
      pgSchema: ctx.schema,
    });

    // Should have blocked operations (dropping the level column)
    expect(plan.blocked.length).toBeGreaterThan(0);

    const sql = generateSql(plan, { includeBlocked: true });

    // Blocked operations should appear as comments
    expect(sql).toContain('-- BLOCKED (destructive)');
    expect(sql).toMatch(/^-- /m);
    // The blocked SQL should contain the drop column
    expect(sql).toContain('level');
  });

  // ─── (4) SQL file written to disk with --output ──

  it('(4) SQL written to disk with generateSqlFile', async () => {
    ctx = await useTestProject(DATABASE_URL);

    writeSchema(ctx.dir, {
      'tables/events.yaml': `
table: events
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
    nullable: false
  - name: created_at
    type: timestamptz
    default: "now()"
`,
    });

    const config = makeConfig(ctx);
    const logger = makeLogger();
    const { desired, actual } = await buildDesiredAndActual(config, logger);
    const plan = buildPlan(desired, actual, {
      allowDestructive: false,
      pgSchema: ctx.schema,
    });

    const outputPath = path.join(os.tmpdir(), `test-migration-${Date.now()}.sql`);
    try {
      generateSqlFile(plan, outputPath, { wrapInTransaction: true });

      expect(fs.existsSync(outputPath)).toBe(true);
      const content = fs.readFileSync(outputPath, 'utf-8');
      expect(content).toContain('BEGIN;');
      expect(content).toContain('COMMIT;');
      expect(content).toContain('events');
    } finally {
      if (fs.existsSync(outputPath)) {
        fs.unlinkSync(outputPath);
      }
    }
  });
});

describe('E2E: ERD generation', () => {
  // ─── (5) generateErd produces valid Mermaid syntax ──

  it('(5) generateErd produces valid Mermaid syntax', () => {
    const tables = [
      parseTable(`
table: users
columns:
  - name: id
    type: serial
    primary_key: true
  - name: email
    type: text
    nullable: false
`),
    ];

    const erd = generateErd(tables);

    expect(erd).toMatch(/^erDiagram/);
    expect(erd).toContain('users');
  });

  // ─── (6) Tables with columns and types rendered ──

  it('(6) tables with columns and types rendered', () => {
    const tables = [
      parseTable(`
table: products
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
  - name: price
    type: numeric
`),
    ];

    const erd = generateErd(tables);

    expect(erd).toContain('products {');
    expect(erd).toContain('serial id PK');
    expect(erd).toContain('text name');
    expect(erd).toContain('numeric price');
  });

  // ─── (7) FK relationships rendered as edges ──

  it('(7) FK relationships rendered as edges', () => {
    const tables = [
      parseTable(`
table: authors
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
`),
      parseTable(`
table: books
columns:
  - name: id
    type: serial
    primary_key: true
  - name: title
    type: text
  - name: author_id
    type: integer
    nullable: false
    references:
      table: authors
      column: id
`),
    ];

    const erd = generateErd(tables);

    // Should have a relationship edge
    expect(erd).toContain('authors');
    expect(erd).toContain('books');
    // FK relationship line
    expect(erd).toMatch(/authors\s+\|\|--o\{\s+books\s*:\s*"author_id"/);
  });

  // ─── (8) Composite PKs rendered correctly ──

  it('(8) composite PKs rendered correctly', () => {
    const tables = [
      parseTable(`
table: order_items
columns:
  - name: order_id
    type: integer
  - name: product_id
    type: integer
  - name: quantity
    type: integer
primary_key:
  - order_id
  - product_id
`),
    ];

    const erd = generateErd(tables);

    expect(erd).toContain('order_items {');
    // Both PK columns should have PK marker
    expect(erd).toContain('integer order_id PK');
    expect(erd).toContain('integer product_id PK');
  });

  // ─── (9) ERD written to file with --output ──

  it('(9) ERD written to file', () => {
    const tables = [
      parseTable(`
table: categories
columns:
  - name: id
    type: serial
    primary_key: true
  - name: name
    type: text
`),
    ];

    const erd = generateErd(tables);
    const outputPath = path.join(os.tmpdir(), `test-erd-${Date.now()}.mmd`);
    try {
      fs.writeFileSync(outputPath, erd, 'utf-8');

      expect(fs.existsSync(outputPath)).toBe(true);
      const content = fs.readFileSync(outputPath, 'utf-8');
      expect(content).toMatch(/^erDiagram/);
      expect(content).toContain('categories');
    } finally {
      if (fs.existsSync(outputPath)) {
        fs.unlinkSync(outputPath);
      }
    }
  });
});
